name: Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run unit tests (Docker)
        run: make ci-unit-test

      - name: Cleanup docker
        if: always()
        run: docker rm -f mdshare-test 2>/dev/null || true

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: "0"
        with:
          name: test-results
          path: test-results/
